### ISSUE TITLE
Funcionalidad: Buscar Pandilla

### ISSUE THREAD

**Issue by 05K4R1N** [Capriatto/Informe-Policial#1]
Bueno bro, la duda que tenia es que si vamos a usar una consulta de la base de datos que sea la siguiente: SELECT * FROM BANDA WHERE LIKE ?
o una que ya la hice en el proyecto... la verdad es que tenia esa duda, hare otra parte del proyecto hasta mientras bro... saludos :v

**Comment by Capriatto** [comment]
Si! Me parece óptimo usar el like de mysql.
