### ISSUE TITLE
Consulta Like

### ISSUE THREAD

**Issue by 05K4R1N** [Capriatto/Informe-Policial#2]
Yo veo mas conveniente una pequeña busqueda, pero al momento de usar un tipo de consulta con LIKE se me complico las cosas, la verdad es que si es que llegas a tener disponibilidad de tiempo seria genial que lo hicieras funcionar con el jLIst.... hasta mientras yo podria hacer otras funcionalidades

**Comment by Capriatto** [comment]
De acuerdo, lo revisaré lo antes posible.

**Comment by 05K4R1N** [comment]
Gracias
