### ISSUE TITLE
Manejo de parametros

### ISSUE THREAD

**Issue by 05K4R1N** [Capriatto/Informe-Policial#3]
Sebas resulta ser que toy en un dilema...
Estaba pensando en agregar dos nuevos atributos a mi clase Delincuente:
De las que ya hay quiero poner ma el nombre del  archivo y el File, osea tipo de cadena de texto y otro File.
Lo que sucede es que no me parece bien la idea de hacer una instancia de la clase donde manejo mis consultas de la BD en java de la interfaz a un archivo .java donde manejo solo consultas, no se... se veo feo.... tu como recomiendas que podria manejar mis dos parametros
asi esta
private int codigo;
private String nombre_completo;
private int identidad;
private int banda_id;
//añadir
private String nombre_de_la_foto;
private FileInputStream foto;
.... espero tu respuesta

**Comment by Capriatto** [comment]
Lo más honesto con el paradigma MVC sería que crees una función en el controlador que permita hacer la consulta insert, por otro lado el controlador podría ser una clase estática para evitar instanciar objetos todo el tiempo. Es solo una recomendación. Piensa lo.

**Comment by 05K4R1N** [comment]
pero que te pareceria la idea de poner dos atributos?? queda?....mmmm
una idea loca puede ser que el nombre de la fotografia y elarchivo no sean considerados como atributos de la clase Delincuente....

**Comment by Capriatto** [comment]
A mi parecer solo debería existir el atributo nombre_foto tipo String y por otro lado tener la variable FileInputStream localmente en la función.

**Comment by 05K4R1N** [comment]
en la Clase Delincuente? como atributos?

**Comment by 05K4R1N** [comment]
![bd](https://cloud.githubusercontent.com/assets/5255678/6120203/108fcf0a-b0a9-11e4-903d-396384acab5a.png)

**Comment by 05K4R1N** [comment]
Ojo ahi ves q lo tengo tal como me dijiste :3

**Comment by Capriatto** [comment]
Solo el nombre de la foto como atributo, el fileinputstream como variable local

**Comment by 05K4R1N** [comment]
Listo ! Ya funciona, pero tuve que agregar un nuevo atributo a Persona Detenida... la BD de datos cambio algunas cosas, podria modificar el .ignore para permitir subir el codigo sql???

**Comment by Capriatto** [comment]
Hecho!
